# This workflow will build a middleman project with bundle

name: Publish

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [ workflow_dispatch ]

permissions:
  id-token: write
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: "${{ secrets.AWS_ROLE_TO_ASSUME }}"
          aws-region: "${{ secrets.AWS_REGION }}"
      - name: Set up upstream and publish to S3
        env:
          BASE_URL: 'https://www.gocd.org'
          DEPLOY_ENVIRONMENT: 'live'
          AWS_BUCKET: "${{ secrets.AWS_BUCKET }}"
          RUN_EXTERNAL_CHECKS: false
        run: |
          bundle exec rake publish --trace